apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-test
  namespace: default
spec:
  selector:
    matchLabels:
      app: gitops-test
  template:
    metadata:
      labels:
        app: gitops-test
    spec:
      containers:
      - image: ghcr.io/activa-prefapp/gitops-app-test:a47a8ffef873f07eba56d4461e4d0f432a71faf6
        imagePullPolicy: IfNotPresent
        name: gitops-test
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 100m
            memory: 250Mi
      imagePullSecrets:
        - name: git-registry-secret