apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitops-test-ingress
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/certificate-id: 558d8574-fb25-40f7-9db2-de9d93de3eb4
    alb.ingress.kubernetes.io/group.name: default-group
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/target-type: ip
    external-dns.alpha.kubernetes.io/hostname: oam-gitops-sample.activa.napptive.dev
spec:
  ingressClassName: alb
  rules:
  - host: oam-gitops-sample.activa.napptive.dev
    http:
      paths:
      - backend:
          service:
            name: gitops-test-service
            port:
              number: 80
        path: /
        pathType: Prefix