apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: oam-app-test
  namespace: default
spec:
  components:
    - name: oam-app-test
      type: helm
      properties:
        repoType: "helm"
        url: "https://prefapp.github.io/charts/aws-web-service"
        chart: "aws-web-service"
        version: "0.3.2"
        values:
          webService:
            # image: ghcr.io/activa-prefapp/oam-app-test:47bfcf9b0d061e46c66d7027971f4245f2e570e4
            image: ubuntu/nginx:latest
          deployment:
            containerPort: 80
          service:
            port: 80
          ingress:
            enabled: "false"
            ingressClassName: "alb"
            host: "oam-gitops-sample.activa.napptive.dev"
            alb:
              enabled: "true"
              # groupName: "group1"
              # protocol: "HTTPS"
              # listenPorts: '[{"HTTP": 80}]'
            annotations:
              alb.ingress.kubernetes.io/certificate-id: "558d8574-fb25-40f7-9db2-de9d93de3eb4"