name: Docker Build and Publish
on:
  push:
    branches:
      - sample-test
    # paths:
    #   - "app/**"

env:
  IMAGE_NAME: oam-app-test
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f app/Dockerfile .
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      
      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      
      - name: Update YAML file
        env:
          GITHUB_TOKEN: ${{ secrets.REGISTRY_TOKEN  }}
        run: |
          # Install yq
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt-get update
          sudo apt-get install yq -y

          # Update image in YAML file
          yq eval '.spec.components[].properties.values.webService.image = "ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"' oam-app/oam-app.yaml -i
          
          # Commit and push changes
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add oam-app/oam-app.yaml
          git commit -m "Update image to ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
          git push origin HEAD:${{ github.ref }}
        shell: bash
