name: Docker Build and Publish
on:
  push:
    branches:
      - sample-test
    # paths:
    #   - "app/**"

env:
  IMAGE_NAME: oam-app-test
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f app/Dockerfile .
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      
      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      
      - name: Update application image version
        uses: yijunyu/update-yaml@v1
        with:
          path: './oam-app/oam-app.yaml'
          expression: '(.spec.components[] | select(.name == "oam-app-test").properties.values.webService.image) |= "ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"'